services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: welcome-app
    image: ghcr.io/fiqrimaulanaar/testing/welcome:latest
    restart: unless-stopped
    ports: 
      - ${APP_PORT}:5000