apiVersion: v1
kind: ConfigMap
metadata:
  name: welcome-app-config
data:
  environment: "production"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
  labels:
    app: welcome-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      volumes:
        - name: welcome-app-config
          configMap:
            name: welcome-app-config
      containers:
        - name: welcome-app
          image: ghcr.io/fiqrimaulanaar/testing/welcome:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: welcome-app-config
              mountPath: /app/config
          env:
            - name: env
              valueFrom:
                configMapKeyRef:
                  name: welcome-app-config
                  key: environment

---
apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service

spec:
  selector:
    app: welcome-app
  ports:
    - port: 8000
      targetPort: 5000

---
apiVersion: v1
kind: Secret
metadata:
  name: welcome-app-secret-tls
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlESVRDQ0FnbWdBd0lCQWdJVUhLL1JkMzFxTzhNYkVYM3NWY3ZuUzB6VmV4MHdEUVlKS29aSWh2Y05BUUVMDQpCUUF3SURFZU1Cd0dBMVVFQXd3VmQyVnNZMjl0WlMxaGNIQXViRzlqWVd4b2IzTjBNQjRYRFRJMU1ESXlPREV3DQpNell6TkZvWERUSTJNREl5T0RFd016WXpORm93SURFZU1Cd0dBMVVFQXd3VmQyVnNZMjl0WlMxaGNIQXViRzlqDQpZV3hvYjNOME1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNlBQTmNrcncyNERqDQpZQ3JBTVlZRlJDOWM3KzlPcHJ2cmM5cHFsK012bzFqc1NXNk03Y2Qwb2U1eis1SU5ob3NEYkFYVnFLMzAxK1VmDQpvMk12c3QzSHJrYnRraFJiZFp5eDIwR2VJVlB3UC80S2hYeitGQ3ZXeHlvckVYTm1TbVRHaFVMYlFLdzB4Z2NpDQoyRElpK0hEZHEvS1YyZ3FrZlB6ZWVVNHN5bE0xWERpK2FVUnlBZmRLdy9ESE50T2tVb0RlNmhobXZaOFdId3FwDQpmanlQN1pEaHNkaTVxM0h0OTQ5blhHNTlXeE8wemhDTFUvVWFqeWlFcGs1dWdtbll1ZXF3akxGS09rZXJzZmZzDQpKU2NKR2k2M2hPczM0Z21MUTlFRDdOeFpOK2k0cnhid25wcWdPcnVQdm92T2xRVEJKWjFtVmRZd05KYUtNTlBGDQpqV3JXeTc0NGhRSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVXbDJDOW5PcFZHWHpIWjRUL1lBSWJVQ0pQZUV3DQpId1lEVlIwakJCZ3dGb0FVV2wyQzluT3BWR1h6SFo0VC9ZQUliVUNKUGVFd0R3WURWUjBUQVFIL0JBVXdBd0VCDQovekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZjUvRURIaGdwSW5CUmVqN3dHQVpwam1ydkZGKytSdEtveEFiDQprTE1SQ2dGU24zblNjL05ZOTR2RXlPcjZNSkZpS01nTW1RMUwza05oSS9UTFVpdUxlMWNSYzJ5NjdmNk5NRkZIDQozUGV0V0lTM045Y0ZNaW5hbm0weWxsUTNkS2lBVzVqTlRlOTQ3RHBPTElVRCtDdUdhYlBqV25Vd0tFUTlUQUthDQpLc2tnMDA5THJVaG1RNE1Rb2laV2Y1QUZmdXZGVmZ0RmtTdldmbXV3WlpFTkNDeC91SjlvRS9EaWw4bk5PNVdMDQpqS1VERlVRYVBFaGtyTnZlbG5UTGUzajFDWmdHZzcxUm5ZeWNpQ01OUlNGdWVNK0pFcFQyU2JyVC85Z2J0RVhRDQpzZWhueGpkVWhrWU12enh3emJBbW14UGJvbzN6VitER2N3NXlhVUpQa1EyVnkzQkRxZz09DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURvODgxeVN2RGJnT05nDQpLc0F4aGdWRUwxenY3MDZtdSt0ejJtcVg0eStqV094SmJvenR4M1NoN25QN2tnMkdpd05zQmRXb3JmVFg1UitqDQpZeSt5M2NldVJ1MlNGRnQxbkxIYlFaNGhVL0EvL2dxRmZQNFVLOWJIS2lzUmMyWktaTWFGUXR0QXJEVEdCeUxZDQpNaUw0Y04ycjhwWGFDcVI4L041NVRpektVelZjT0w1cFJISUI5MHJEOE1jMjA2UlNnTjdxR0dhOW54WWZDcWwrDQpQSS90a09HeDJMbXJjZTMzajJkY2JuMWJFN1RPRUl0VDlScVBLSVNtVG02Q2FkaTU2ckNNc1VvNlI2dXg5K3dsDQpKd2thTHJlRTZ6ZmlDWXREMFFQczNGazM2TGl2RnZDZW1xQTZ1NCsraTg2VkJNRWxuV1pWMWpBMGxvb3cwOFdODQphdGJMdmppRkFnTUJBQUVDZ2dFQUhMK1REL0wzVk16TUFyUmVsMGl0VjE2cStheWtTRjBIbW5xNWVJNGZ5bWtHDQpjVmQvSCtHNHRJL2d2Z3FtWXY5cE10MitJanpPNncwMUxDem83WW91TFlWR1VLYWZmNGU3Y1U0TFF2SUF3N3p6DQp0UjZablRQOXpsZ1hZWkRHdzd2bEUxRmtEU1ZUWVVtWjFMN01qd2JLd2RZWnI5akJZa1ZkK3ByRVdmY09nNWRSDQpmd2RUVUJmN2EzS21WemU0VDkyVDA5eTY3d3picEZyZ2F2RXR5UjhxWUZNbnhtVTR5dHQ0OGVQSDFPMStQN2VmDQp0UEV1SXA3OG5VRmxMU0dsT3MrY0M1bDdmdXlxQ0FPUXphTnFvcmp4ZGhSMHBpbXVMS28xZHdCOUpaMUFvYlZwDQoveSswMGd5dzRLS2E3VU5FMTVMSHk2KzhyNE5oK04xb2kzdm5EME1tZndLQmdRRDZETHNENkkxMzZYYnlDN2xQDQpxNkFwbW9VRkpsQkxPbW4vTTYzQ3EzdjRDUlZDODBzUGxNU1J0UFBUL0hocGhYaDQ2TmFIVXA4Y3N4czFuZU0wDQpKY3crdmZ4Q0RjTFluNU5IaHFKSFFzMDREL3MvNk1hMTAxM1BUV3ZCV2VkTklUaUJwNDdjc1J5SFdWUkVaSjZ6DQp3VjFtRmtTSnZLbmZ3NytGOXlQOFhlTStTd0tCZ1FEdWZ1ckZrWFRsZE8xaHFYLzE2SE1LeDV4VEFEeXhHYUVNDQpCTXhIanlBWXYzVVZjY01ZR0s5N2lJMkUrOVI5WTFnckFVcjkzcEtPaFh5c2lobTNHM0xzbjMzSGpaTjhmSEp0DQpuekV3OVUraEo4Z2tmK3ZoQkxiRTJlbjV6VS9pVml6RnFjd0NuajlyRVNOUk1wcFVEalJCdTZxdnA5UU9iMUI3DQpDMW0weUtqaWJ3S0JnRDgxcnFUN1NaL1JkYzhVSmFFOU9ueXA0Z3grTmZmK2FVTXBGampLenNqUnl2MGtzWW5iDQp5cUVteENpSGZ3ejF2NUdaRW5vYzZib0FrTlZKOTJCOFdaaFd3SWtXSDNaUlNKTGhOdTZhdFhRQm5qcjJwaHphDQp0TEV0MmhxRGxwUUozTlh4dkl5UGZTMjk2QzV0M1N5RnFnMmZmVzN3TW1VdGY2SG02c0xtSFFibkFvR0JBSjMzDQpVbWtwdnROOGJ2NlExa0I2aGpoTm5pMGJxeGRpY2xrVGxIcVJRaUVpTHRyVlR2Tlc1bVJjUGVBbkxNY2dWZldtDQpGWld4SmtGZ0NRUC9OS2tqZFN0bE9GcEVXN3ZJY2NKSi9ycit3STl0V2hOUzUxbFRWZnRzbXB6cWNFN3A1UjNIDQpLV2xTaDQ3Uyt5Rjg4dHRaelNMOHVrRStXQ1ozZEVjTGJZOWdtUHZoQW9HQkFMM3E5aWlYN3hJR3huNnh0UmdZDQphKzF5cE5DVkpEa2VCK2prd1E2WkJneDNWVi95KzdXcG5qZElaYkcxSWFDR0RacEtTQnlDeSt4OGV4cVZLcDNMDQp1WlgzOGVadzlqUEV2VUoxRXp1V1RBbDRibU5GclNYRHhwK2R4d3VoVG9EUCt2NHA5bGVtMHBsR3pWVS9XY3lFDQozWUhTUFFNVTFJaHV6cng2TlRSejZGODcNCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg==

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: welcome-app-ingress

spec:
  tls:
    - hosts:
        - welcome-app.localhost-tls
      secretName: welcome-app-secret-tls
  rules:
    - host: welcome-app.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: welcome-app-service
                port:
                  number: 8000
