name: "welcome app"

on:
  push:
    branches: ["main"] 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker build
        run: docker build -t ghcr.io/fiqrimaulanaar/testing/welcome:latest .

      - name: Docker login
        run: docker login --username fiqrimaulanaar --password ${{ secrets.PACKAGES_TOKEN }} ghcr.io

      - name: Docker push
        run: docker push ghcr.io/fiqrimaulanaar/testing/welcome:latest
